// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/account/login": {
            "post": {
                "description": "登陆",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "account"
                ],
                "summary": "登陆",
                "parameters": [
                    {
                        "description": "登录信息",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.LoginDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "登录失败",
                        "schema": {
                            "$ref": "#/definitions/handler.Response"
                        }
                    }
                }
            }
        },
        "/api/account/quit": {
            "post": {
                "description": "退出",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "account"
                ],
                "summary": "退出",
                "responses": {
                    "200": {
                        "description": "退出成功",
                        "schema": {
                            "$ref": "#/definitions/handler.Response"
                        }
                    }
                }
            }
        },
        "/api/attendance_record/approve/query/all": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "考勤记录"
                ],
                "summary": "查询主管待审批的考勤记录",
                "responses": {}
            }
        },
        "/api/attendance_record/approve/query/{leader_staff_id}": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "考勤记录"
                ],
                "summary": "查询主管待审批的考勤记录",
                "parameters": [
                    {
                        "type": "string",
                        "description": "主管员工ID",
                        "name": "leader_staff_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/api/attendance_record/approve_accept/{attendId}": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "考勤记录"
                ],
                "summary": "审批通过考勤记录",
                "parameters": [
                    {
                        "type": "string",
                        "description": "考勤记录ID",
                        "name": "attendId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/api/attendance_record/approve_reject/{attendId}": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "考勤记录"
                ],
                "summary": "审批拒绝考勤记录",
                "parameters": [
                    {
                        "type": "string",
                        "description": "考勤记录ID",
                        "name": "attendId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/api/attendance_record/create": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "考勤记录"
                ],
                "summary": "创建考勤记录",
                "parameters": [
                    {
                        "description": "考勤记录",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.AttendanceRecordCreateDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.Response"
                        }
                    }
                }
            }
        },
        "/api/attendance_record/delete/{attendance_id}": {
            "delete": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "考勤记录"
                ],
                "summary": "删除考勤记录",
                "parameters": [
                    {
                        "type": "string",
                        "description": "考勤记录ID",
                        "name": "attendance_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/api/attendance_record/edit": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "考勤记录"
                ],
                "summary": "更新考勤记录",
                "parameters": [
                    {
                        "description": "更新考勤记录信息",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.AttendanceRecordEditDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.AttendanceRecordEditDTO"
                        }
                    }
                }
            }
        },
        "/api/attendance_record/get_attend_record_is_pay/{staff_id}/{date}": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "考勤记录"
                ],
                "summary": "查询员工指定月份考勤记录是否已结算",
                "parameters": [
                    {
                        "type": "string",
                        "description": "员工ID",
                        "name": "staff_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "日期(格式：YYYY-MM)",
                        "name": "date",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/api/attendance_record/query/{staff_id}": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "考勤记录"
                ],
                "summary": "查询员工考勤记录",
                "parameters": [
                    {
                        "type": "string",
                        "description": "员工ID",
                        "name": "staff_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/api/attendance_record/query_history/all": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "考勤记录"
                ],
                "summary": "查询员工历史考勤记录",
                "responses": {}
            }
        },
        "/api/attendance_record/query_history/{staff_id}": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "考勤记录"
                ],
                "summary": "查询员工历史考勤记录",
                "parameters": [
                    {
                        "type": "string",
                        "description": "员工ID",
                        "name": "staff_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/api/authority/create": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "权限管理"
                ],
                "summary": "创建授权",
                "parameters": [
                    {
                        "description": "创建授权",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.AddAuthorityDetailDTO"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/authority/edit": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "权限管理"
                ],
                "summary": "编辑授权",
                "parameters": [
                    {
                        "description": "编辑授权",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.UpdateAuthorityDetailDTO"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/authority/query_by_user_type/{user_type}": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "权限管理"
                ],
                "summary": "根据用户类型查询授权",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户类型",
                        "name": "user_type",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.GetAuthorityDetailDTO"
                        }
                    }
                }
            }
        },
        "/api/authority/query_by_user_type_and_model": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "权限管理"
                ],
                "summary": "根据用户类型和模块查询授权",
                "parameters": [
                    {
                        "description": "根据用户类型和模块查询授权",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.GetAuthorityDetailDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.GetAuthorityDetailDTO"
                        }
                    }
                }
            }
        },
        "/api/authority/set_admin/{staff_id}": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "权限管理"
                ],
                "summary": "设置管理员",
                "parameters": [
                    {
                        "type": "string",
                        "description": "员工ID",
                        "name": "staff_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/api/authority/set_normal/{staff_id}": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "权限管理"
                ],
                "summary": "设置普通用户",
                "parameters": [
                    {
                        "type": "string",
                        "description": "员工ID",
                        "name": "staff_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/api/authority_render/:modelName": {
            "get": {
                "description": "权限重定向",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "account"
                ],
                "summary": "权限重定向",
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/candidate/accept/{id}": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "候选人管理"
                ],
                "summary": "接受候选人",
                "parameters": [
                    {
                        "type": "string",
                        "description": "候选人ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/api/candidate/create": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "候选人管理"
                ],
                "summary": "创建候选人信息",
                "parameters": [
                    {
                        "description": "候选人信息",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.CandidateCreateDTO"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/candidate/delete/{candidate_id}": {
            "delete": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "候选人管理"
                ],
                "summary": "删除候选人信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "候选人ID",
                        "name": "candidate_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/api/candidate/edit": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "候选人管理"
                ],
                "summary": "更新候选人信息",
                "parameters": [
                    {
                        "description": "更新候选人信息",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.CandidateEditDTO"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/candidate/query_by_name/{name}": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "候选人管理"
                ],
                "summary": "根据姓名查询候选人",
                "parameters": [
                    {
                        "type": "string",
                        "description": "候选人姓名",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "页码",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "每页数量",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {}
            }
        },
        "/api/candidate/query_by_staff_id/{staff_id}": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "候选人管理"
                ],
                "summary": "根据员工ID查询候选人",
                "parameters": [
                    {
                        "type": "string",
                        "description": "员工ID",
                        "name": "staff_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "页码",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "每页数量",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {}
            }
        },
        "/api/candidate/reject/{id}": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "候选人管理"
                ],
                "summary": "拒绝候选人",
                "parameters": [
                    {
                        "type": "string",
                        "description": "候选人ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/api/company/query": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "公司"
                ],
                "summary": "查询公司列表",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.BranchCompany"
                        }
                    }
                }
            }
        },
        "/api/depart/create": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "部门管理"
                ],
                "summary": "创建部门",
                "parameters": [
                    {
                        "description": "部门信息",
                        "name": "department",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.DepartmentCreateDTO"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/depart/del/{dep_id}": {
            "delete": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "部门管理"
                ],
                "summary": "删除部门",
                "parameters": [
                    {
                        "type": "string",
                        "description": "部门ID",
                        "name": "dep_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/api/depart/edit": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "部门管理"
                ],
                "summary": "编辑部门",
                "parameters": [
                    {
                        "description": "部门信息",
                        "name": "department",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.DepartmentEditDTO"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/depart/query/{dep_id}": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "部门管理"
                ],
                "summary": "查询部门",
                "parameters": [
                    {
                        "type": "string",
                        "description": "部门ID",
                        "name": "dep_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "页码",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "每页数量",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {}
            }
        },
        "/api/example/create": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "考试管理"
                ],
                "summary": "创建示例/考试",
                "parameters": [
                    {
                        "description": "考试信息",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.ExampleCreateDTO"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/example/delete/{example_id}": {
            "delete": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "考试管理"
                ],
                "summary": "删除考试",
                "parameters": [
                    {
                        "type": "string",
                        "description": "考试ID",
                        "name": "example_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/api/example/edit": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "考试管理"
                ],
                "summary": "更新考试信息",
                "parameters": [
                    {
                        "description": "更新考试信息",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.ExampleEditDTO"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/example/parse_example_content": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "考试管理"
                ],
                "summary": "解析考试内容",
                "responses": {}
            }
        },
        "/api/example/query/{name}": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "考试管理"
                ],
                "summary": "根据名称查询考试",
                "parameters": [
                    {
                        "type": "string",
                        "description": "考试名称",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/api/example/render_example/{id}": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "考试管理"
                ],
                "summary": "渲染考试内容",
                "parameters": [
                    {
                        "type": "string",
                        "description": "考试ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/api/example_score/create": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "考试成绩"
                ],
                "summary": "创建考试成绩记录",
                "parameters": [
                    {
                        "description": "考试成绩信息",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.ExampleScoreCreateDTO"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/example_score/query_by_name/{name}": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "考试成绩"
                ],
                "summary": "根据考试名称查询成绩历史",
                "parameters": [
                    {
                        "type": "string",
                        "description": "考试名称",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/api/example_score/query_by_staff_id/{staff_id}": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "考试成绩"
                ],
                "summary": "根据员工ID查询成绩历史",
                "parameters": [
                    {
                        "type": "string",
                        "description": "员工ID",
                        "name": "staff_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/api/index": {
            "get": {
                "description": "首页重定向",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "account"
                ],
                "summary": "首页重定向",
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/notification/create": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "通知"
                ],
                "summary": "创建通知",
                "parameters": [
                    {
                        "description": "通知",
                        "name": "notification",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.NotificationDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.Response"
                        }
                    }
                }
            }
        },
        "/api/notification/delete/{notice_id}": {
            "delete": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "通知"
                ],
                "summary": "删除通知",
                "parameters": [
                    {
                        "type": "string",
                        "description": "通知ID",
                        "name": "notice_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.Response"
                        }
                    }
                }
            }
        },
        "/api/notification/edit": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "通知"
                ],
                "summary": "修改通知",
                "parameters": [
                    {
                        "description": "通知",
                        "name": "notification",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.NotificationEditDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.Response"
                        }
                    }
                }
            }
        },
        "/api/notification/query/{notice_title}": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "通知"
                ],
                "summary": "根据通知名字查询通知",
                "parameters": [
                    {
                        "type": "string",
                        "description": "通知标题",
                        "name": "notice_title",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "页码",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "每页数量",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.Response"
                        }
                    }
                }
            }
        },
        "/api/password/edit": {
            "post": {
                "description": "修改密码",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "password"
                ],
                "summary": "修改密码",
                "parameters": [
                    {
                        "description": "密码信息",
                        "name": "password",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.PasswordEditDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.Response"
                        }
                    }
                }
            }
        },
        "/api/password/query/{staff_id}": {
            "get": {
                "description": "查询所有密码",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "password"
                ],
                "summary": "查询所有密码",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.PasswordQueryVO"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.Response"
                        }
                    }
                }
            }
        },
        "/api/ping": {
            "get": {
                "description": "ping",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "account"
                ],
                "summary": "ping",
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/rank/create": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Rank"
                ],
                "summary": "创建职级",
                "parameters": [
                    {
                        "description": "创建职级",
                        "name": "rankCreateDTO",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.RankCreateDTO"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/rank/edit": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Rank"
                ],
                "summary": "编辑职级",
                "parameters": [
                    {
                        "description": "编辑职级",
                        "name": "rankEditDTO",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.RankEditDTO"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/rank/{rank_id}/del": {
            "delete": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Rank"
                ],
                "summary": "删除职级",
                "parameters": [
                    {
                        "type": "string",
                        "description": "职级id",
                        "name": "rank_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/api/rank/{rank_id}/query": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Rank"
                ],
                "summary": "查询职级",
                "parameters": [
                    {
                        "type": "string",
                        "description": "职级id",
                        "name": "rank_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/api/recruitment/create": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "招聘管理"
                ],
                "summary": "创建招聘信息",
                "parameters": [
                    {
                        "description": "招聘信息",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.RecruitmentCreateDTO"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/recruitment/delete/{recruitment_id}": {
            "delete": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "招聘管理"
                ],
                "summary": "删除招聘信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "招聘信息ID",
                        "name": "recruitment_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/api/recruitment/edit": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "招聘管理"
                ],
                "summary": "更新招聘信息",
                "parameters": [
                    {
                        "description": "更新招聘信息",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.RecruitmentEditDTO"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/recruitment/query/{job_name}": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "招聘管理"
                ],
                "summary": "根据职位名称查询招聘信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "职位名称",
                        "name": "job_name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/api/salary/create": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Salary"
                ],
                "summary": "创建薪资信息",
                "parameters": [
                    {
                        "description": "薪资信息",
                        "name": "salary",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.SalaryCreateDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.Response"
                        }
                    }
                }
            }
        },
        "/api/salary/delete/{salary_id}": {
            "delete": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Salary"
                ],
                "summary": "删除薪资信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "薪资ID",
                        "name": "salary_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.Response"
                        }
                    }
                }
            }
        },
        "/api/salary/edit": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Salary"
                ],
                "summary": "修改薪资信息",
                "parameters": [
                    {
                        "description": "薪资信息",
                        "name": "salary",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.SalaryEditDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.Response"
                        }
                    }
                }
            }
        },
        "/api/salary/query/all": {
            "get": {
                "consumes": [
                    "application/json",
                    "application/json"
                ],
                "produces": [
                    "application/json",
                    "application/json"
                ],
                "tags": [
                    "Salary",
                    "Salary"
                ],
                "summary": "薪资列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "页码",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "每页数量",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.Response"
                        }
                    }
                }
            }
        },
        "/api/salary/query/{staff_id}": {
            "get": {
                "consumes": [
                    "application/json",
                    "application/json"
                ],
                "produces": [
                    "application/json",
                    "application/json"
                ],
                "tags": [
                    "Salary",
                    "Salary"
                ],
                "summary": "薪资列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "员工ID",
                        "name": "staff_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "页码",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "每页数量",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.Response"
                        }
                    }
                }
            }
        },
        "/api/salary_record/get_salary_record_is_pay_by_id/{id}": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SalaryRecord"
                ],
                "summary": "根据ID查询薪资发放记录是否已发放",
                "parameters": [
                    {
                        "type": "string",
                        "description": "薪资发放记录ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.Response"
                        }
                    }
                }
            }
        },
        "/api/salary_record/pay_salary_record_by_id/{id}": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SalaryRecord"
                ],
                "summary": "根据ID发放薪资",
                "parameters": [
                    {
                        "type": "string",
                        "description": "薪资发放记录ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.Response"
                        }
                    }
                }
            }
        },
        "/api/salary_record/query/{staff_id}": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SalaryRecord"
                ],
                "summary": "根据员工ID查询薪资发放记录",
                "parameters": [
                    {
                        "type": "string",
                        "description": "员工ID",
                        "name": "staff_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.Response"
                        }
                    }
                }
            }
        },
        "/api/salary_record/query_history/all": {
            "get": {
                "consumes": [
                    "application/json",
                    "application/json"
                ],
                "produces": [
                    "application/json",
                    "application/json"
                ],
                "tags": [
                    "SalaryRecord",
                    "SalaryRecord"
                ],
                "summary": "薪资历史记录",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.Response"
                        }
                    }
                }
            }
        },
        "/api/salary_record/query_history/{staff_id}": {
            "get": {
                "consumes": [
                    "application/json",
                    "application/json"
                ],
                "produces": [
                    "application/json",
                    "application/json"
                ],
                "tags": [
                    "SalaryRecord",
                    "SalaryRecord"
                ],
                "summary": "薪资历史记录",
                "parameters": [
                    {
                        "type": "string",
                        "description": "员工ID",
                        "name": "staff_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "员工ID",
                        "name": "staff_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.Response"
                        }
                    }
                }
            }
        },
        "/api/staff/create": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "staff"
                ],
                "summary": "新增员工信息",
                "parameters": [
                    {
                        "description": "员工信息",
                        "name": "staff",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.StaffCreateDTO"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/staff/del/{staff_id}": {
            "delete": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "staff"
                ],
                "summary": "删除员工信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "员工ID",
                        "name": "staff_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/api/staff/edit": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "staff"
                ],
                "summary": "编辑员工信息",
                "parameters": [
                    {
                        "description": "员工信息",
                        "name": "staff",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.StaffCreateDTO"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/staff/excel_export": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "staff"
                ],
                "summary": "导出员工信息",
                "responses": {}
            }
        },
        "/api/staff/query/{staff_id}": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "staff"
                ],
                "summary": "根据员工ID查询员工信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "员工ID",
                        "name": "staff_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/api/staff/query_by_dep/{dep_name}": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "staff"
                ],
                "summary": "根据部门查询员工信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "部门名称",
                        "name": "dep_name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/api/staff/query_by_name/{staff_name}": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "staff"
                ],
                "summary": "根据员工姓名查询员工信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "员工姓名",
                        "name": "staff_name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/api/staff/query_by_staff_id/{staff_id}": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "staff"
                ],
                "summary": "根据员工ID查询员工信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "员工ID",
                        "name": "staff_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        }
    },
    "definitions": {
        "handler.Response": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "状态码",
                    "type": "integer"
                },
                "data": {
                    "description": "响应数据"
                },
                "message": {
                    "description": "响应消息"
                },
                "status": {
                    "description": "状态码",
                    "type": "boolean"
                }
            }
        },
        "model.AddAuthorityDetailDTO": {
            "type": "object",
            "required": [
                "authority_content",
                "model",
                "name",
                "user_type"
            ],
            "properties": {
                "authority_content": {
                    "type": "string"
                },
                "model": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "user_type": {
                    "type": "string"
                }
            }
        },
        "model.AttendanceRecordCreateDTO": {
            "type": "object",
            "properties": {
                "date": {
                    "type": "string"
                },
                "leave_days": {
                    "type": "integer"
                },
                "overtime_days": {
                    "type": "integer"
                },
                "staff_id": {
                    "type": "string"
                },
                "staff_name": {
                    "type": "string"
                },
                "work_days": {
                    "type": "integer"
                }
            }
        },
        "model.AttendanceRecordEditDTO": {
            "type": "object",
            "properties": {
                "date": {
                    "type": "string"
                },
                "id": {
                    "type": "integer",
                    "format": "int64"
                },
                "leave_days": {
                    "type": "integer"
                },
                "overtime_days": {
                    "type": "integer"
                },
                "staff_id": {
                    "type": "string"
                },
                "staff_name": {
                    "type": "string"
                },
                "work_days": {
                    "type": "integer"
                }
            }
        },
        "model.BranchCompany": {
            "type": "object",
            "properties": {
                "branch_id": {
                    "type": "string"
                },
                "desc": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "model.CandidateCreateDTO": {
            "type": "object",
            "properties": {
                "describe": {
                    "type": "string"
                },
                "edu_level": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "experience": {
                    "type": "string"
                },
                "job_name": {
                    "type": "string"
                },
                "major": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "staff_id": {
                    "type": "string"
                }
            }
        },
        "model.CandidateEditDTO": {
            "type": "object",
            "properties": {
                "describe": {
                    "type": "string"
                },
                "edu_level": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "evaluation": {
                    "type": "string"
                },
                "experience": {
                    "type": "string"
                },
                "id": {
                    "type": "integer",
                    "format": "int64"
                },
                "job_name": {
                    "type": "string"
                },
                "major": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "staff_id": {
                    "type": "string"
                }
            }
        },
        "model.DepartmentCreateDTO": {
            "type": "object",
            "required": [
                "dep_describe",
                "dep_name"
            ],
            "properties": {
                "dep_describe": {
                    "type": "string"
                },
                "dep_name": {
                    "type": "string"
                }
            }
        },
        "model.DepartmentEditDTO": {
            "type": "object",
            "required": [
                "dep_describe",
                "dep_id",
                "dep_name"
            ],
            "properties": {
                "dep_describe": {
                    "type": "string"
                },
                "dep_id": {
                    "type": "string"
                },
                "dep_name": {
                    "type": "string"
                }
            }
        },
        "model.ExampleCreateDTO": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "date": {
                    "type": "string"
                },
                "describe": {
                    "type": "string"
                },
                "limit": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "model.ExampleEditDTO": {
            "type": "object",
            "required": [
                "id"
            ],
            "properties": {
                "date": {
                    "type": "string"
                },
                "describe": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "limit": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "model.ExampleScoreCreateDTO": {
            "type": "object",
            "required": [
                "commit",
                "content",
                "example_id",
                "staff_id"
            ],
            "properties": {
                "commit": {
                    "type": "string"
                },
                "content": {
                    "type": "string"
                },
                "date": {
                    "type": "string"
                },
                "example_id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "staff_id": {
                    "type": "string"
                },
                "staff_name": {
                    "type": "string"
                }
            }
        },
        "model.GetAuthorityDetailDTO": {
            "type": "object",
            "required": [
                "model",
                "user_type"
            ],
            "properties": {
                "model": {
                    "type": "string"
                },
                "user_type": {
                    "type": "string"
                }
            }
        },
        "model.LoginDTO": {
            "type": "object",
            "required": [
                "branch_id",
                "staff_id",
                "user_password"
            ],
            "properties": {
                "branch_id": {
                    "type": "string"
                },
                "staff_id": {
                    "type": "string"
                },
                "user_password": {
                    "type": "string"
                }
            }
        },
        "model.NotificationDTO": {
            "type": "object",
            "required": [
                "date",
                "notice_content",
                "notice_title",
                "type"
            ],
            "properties": {
                "date": {
                    "type": "string"
                },
                "notice_content": {
                    "type": "string"
                },
                "notice_title": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "model.NotificationEditDTO": {
            "type": "object",
            "required": [
                "id"
            ],
            "properties": {
                "date": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "notice_content": {
                    "type": "string"
                },
                "notice_id": {
                    "type": "string"
                },
                "notice_title": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "model.PasswordEditDTO": {
            "type": "object",
            "properties": {
                "password": {
                    "type": "string"
                },
                "staff_id": {
                    "type": "string"
                }
            }
        },
        "model.PasswordQueryVO": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "password": {
                    "type": "string"
                },
                "staff_id": {
                    "type": "string"
                },
                "staff_name": {
                    "type": "string"
                }
            }
        },
        "model.RankCreateDTO": {
            "type": "object",
            "required": [
                "rank_name"
            ],
            "properties": {
                "rank_name": {
                    "type": "string"
                }
            }
        },
        "model.RankEditDTO": {
            "type": "object",
            "required": [
                "rank_id",
                "rank_name"
            ],
            "properties": {
                "rank_id": {
                    "type": "string"
                },
                "rank_name": {
                    "type": "string"
                }
            }
        },
        "model.RecruitmentCreateDTO": {
            "type": "object",
            "required": [
                "base_location",
                "base_salary",
                "describe",
                "edu_level",
                "email",
                "experience",
                "job_name",
                "job_type"
            ],
            "properties": {
                "base_location": {
                    "type": "string"
                },
                "base_salary": {
                    "type": "string"
                },
                "describe": {
                    "type": "string"
                },
                "edu_level": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "experience": {
                    "type": "string"
                },
                "job_name": {
                    "type": "string"
                },
                "job_type": {
                    "type": "string"
                }
            }
        },
        "model.RecruitmentEditDTO": {
            "type": "object",
            "required": [
                "id"
            ],
            "properties": {
                "base_location": {
                    "type": "string"
                },
                "base_salary": {
                    "type": "string"
                },
                "describe": {
                    "type": "string"
                },
                "edu_level": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "experience": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "job_name": {
                    "type": "string"
                },
                "job_type": {
                    "type": "string"
                }
            }
        },
        "model.SalaryCreateDTO": {
            "type": "object",
            "properties": {
                "base": {
                    "type": "integer"
                },
                "bonus": {
                    "type": "integer"
                },
                "commission": {
                    "type": "integer"
                },
                "fund": {
                    "type": "integer"
                },
                "other": {
                    "type": "integer"
                },
                "staff_id": {
                    "type": "string"
                },
                "staff_name": {
                    "type": "string"
                },
                "subsidy": {
                    "type": "integer"
                }
            }
        },
        "model.SalaryEditDTO": {
            "type": "object",
            "properties": {
                "base": {
                    "type": "integer"
                },
                "bonus": {
                    "type": "integer"
                },
                "commission": {
                    "type": "integer"
                },
                "fund": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer",
                    "format": "int64"
                },
                "other": {
                    "type": "integer"
                },
                "staff_id": {
                    "type": "string"
                },
                "staff_name": {
                    "type": "string"
                },
                "subsidy": {
                    "type": "integer"
                }
            }
        },
        "model.StaffCreateDTO": {
            "type": "object",
            "required": [
                "base_salary",
                "birthday_str",
                "card_num",
                "dep_id",
                "edu_level",
                "email",
                "entry_date_str",
                "identity_num",
                "major",
                "nation",
                "phone",
                "rank_id",
                "school",
                "sex_str",
                "staff_name"
            ],
            "properties": {
                "base_salary": {
                    "type": "integer"
                },
                "birthday_str": {
                    "type": "string"
                },
                "card_num": {
                    "type": "string"
                },
                "dep_id": {
                    "type": "string"
                },
                "edu_level": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "entry_date_str": {
                    "type": "string"
                },
                "identity_num": {
                    "type": "string"
                },
                "leader_name": {
                    "type": "string"
                },
                "leader_staff_id": {
                    "type": "string"
                },
                "major": {
                    "type": "string"
                },
                "nation": {
                    "type": "string"
                },
                "phone": {
                    "type": "integer"
                },
                "rank_id": {
                    "type": "string"
                },
                "school": {
                    "type": "string"
                },
                "sex_str": {
                    "type": "string"
                },
                "staff_name": {
                    "type": "string"
                }
            }
        },
        "model.UpdateAuthorityDetailDTO": {
            "type": "object",
            "required": [
                "authority_content",
                "id"
            ],
            "properties": {
                "authority_content": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
