name: hrms Docker Build and Push

on:
  workflow_dispatch: # 手动触发
  push:
    paths:
      - "config/**"
      - "frontend/**"
      - "model/**"
      - "resource/**"
      - "server/**"
      - "sql/**"
      - "dockerfile"
      - "go.mod"
      - "go.sum"
      - "main.go"
    branches: [main] # 当推送到 main 分支时触发

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      matrix:
        platform: [linux/amd64, linux/arm64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Extract platform
        id: platform
        run: echo "PLATFORM=${{ matrix.platform }}" | tr '/' '_' >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          platforms: ${{ matrix.platform }}
          tags: |
            codeyhj/hrms-docker:latest-${{ steps.platform.outputs.PLATFORM }}
          cache-from: type=gha,scope=${{ matrix.platform }}
          cache-to: type=gha,mode=max,scope=${{ matrix.platform }}
